### ISSUE TITLE
Does not work with clojure 1.8.0

### ISSUE THREAD

**Issue by s4s0l** [wkf/docker-client-clj#5]
just FYI

Caused by: java.lang.NoClassDefFoundError: IllegalName: compile__stub.clj_http.headers.clj-http.headers/HeaderMap
        at java.lang.ClassLoader.preDefineClass(ClassLoader.java:654)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
        at clojure.lang.DynamicClassLoader.defineClass(DynamicClassLoader.java:46)
        at clojure.lang.Compiler$NewInstanceExpr.compileStub(Compiler.java:7903)
        at clojure.lang.Compiler$NewInstanceExpr.build(Compiler.java:7768)
        at clojure.lang.Compiler$NewInstanceExpr$DeftypeParser.parse(Compiler.java:7678)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
        ... 193 more
clj-http needs updating

**Comment by wkf** [comment]
Thanks for the report!
